---
- name: Check if STONITH resource already exists
  ansible.builtin.shell: pcs stonith config fence-kdump
  delegate_to: "{{ infra__redhat_cluster_nodes[0].hostname }}"
  register: stonith_check
  changed_when: false
  failed_when: false
  ignore_errors: true
  run_once: true
  tags: stonith

- name: Check STONITH resource configuration
  ansible.builtin.shell: pcs stonith config fence-kdump
  delegate_to: "{{ infra__redhat_cluster_nodes[0].hostname }}"
  register: stonith_config
  changed_when: false
  failed_when: false
  when: stonith_check.rc == 0
  run_once: true
  tags: stonith

- name: Create STONITH resource with fence_kdump
  ansible.builtin.shell: >
    pcs stonith create fence-kdump fence_kdump pcmk_host_list="{{ infra__redhat_cluster_nodes | map(attribute='hostname') | join(',') }}" ipport=7410
  run_once: true
  delegate_to: "{{ infra__redhat_cluster_nodes[0].hostname }}"
  register: create_stonith
  failed_when: create_stonith.rc != 0 and "already exists" not in create_stonith.stderr
  when: stonith_check.rc != 0
  tags: stonith

- name: Update STONITH resource with fence_kdump if configuration changed
  ansible.builtin.shell: >
    pcs stonith update fence-kdump pcmk_host_list="{{ infra__redhat_cluster_nodes | map(attribute='hostname') | join(',') }}" ipport=7410
  run_once: true
  delegate_to: "{{ infra__redhat_cluster_nodes[0].hostname }}"
  register: update_stonith
  when:
    - stonith_check.rc == 0
    - stonith_config.stdout is defined
    - (("pcmk_host_list=" + infra__redhat_cluster_nodes | map(attribute='hostname') | join(',')) not in stonith_config.stdout) or "ipport=7410" not in stonith_config.stdout
  tags: stonith

- name: Check if STONITH is enabled
  ansible.builtin.shell: pcs property config | grep stonith-enabled
  delegate_to: "{{ infra__redhat_cluster_nodes[0].hostname }}"
  register: stonith_enabled_check
  changed_when: false
  failed_when: false
  run_once: true
  tags: stonith

- name: Enable STONITH
  ansible.builtin.shell: pcs property set stonith-enabled=true
  run_once: true
  delegate_to: "{{ infra__redhat_cluster_nodes[0].hostname }}"
  when: stonith_enabled_check.rc != 0 or "stonith-enabled=true" not in stonith_enabled_check.stdout
  tags: stonith
