---
- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ infra__redhat_cluster_required_packages }}"
    state: present
  tags: packages

- name: Load softdog module
  ansible.builtin.modprobe:
    name: softdog
    state: present
  tags: watchdog

- name: Ensure softdog module loads at boot
  ansible.builtin.copy:
    content: "softdog\n"
    dest: /etc/modules-load.d/softdog.conf
    owner: root
    group: root
    mode: '0644'
  tags: watchdog

- name: Enable and start pcsd service
  ansible.builtin.systemd:
    name: pcsd
    enabled: yes
    state: started
  tags: services
  
