---
- name: Update all packages
  dnf:
    name: "*"
    state: latest
  tags: update

- name: Set hostname
  hostname:
    name: "{{ ansible_hostname }}"
  tags: hostname

- name: Configure /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  tags: hosts

- name: Configure firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ firewall_services }}"
  tags: firewall

- name: Reload firewall
  command: firewall-cmd --reload
  changed_when: false
  tags: firewall

- name: Create mount point directory
  file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0755'
  tags: nfs

- name: Create temporary mount point for NFS setup
  file:
    path: "/tmp/nfs_temp_mount"
    state: directory
    mode: '0755'
  run_once: true
  delegate_to: "{{ cluster_nodes[0].hostname }}"
  tags: watchdog
