---
- name: Set hostname based on cluster_nodes definition
  ansible.builtin.hostname:
    name: "{{ item.hostname }}"
  when:
    - infra__redhat_cluster_set_cluster_hostname | bool
    - inventory_hostname == item.hostname
  loop: "{{ infra__redhat_cluster_nodes }}"
  tags: hostname

- name: Add cluster nodes to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ item.ip }}\\s+"
    line: "{{ item.ip }} {{ item.hostname }}"
    state: present
  with_items: "{{ infra__redhat_cluster_nodes }}"
  tags: hosts

- name: Add virtual IP to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ infra__redhat_cluster_virtual_ip }}\\s+"
    line: "{{ infra__redhat_cluster_virtual_ip }} {{ infra__redhat_cluster_dns_for_virtual_ip }}"
    state: present
  tags: hosts

- name: Configure firewall
  ansible.builtin.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ infra__redhat_cluster_firewall_services }}"
  tags: firewall

- name: Reload firewall
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false
  tags: firewall

- name: Create mount point directory
  ansible.builtin.file:
    path: "{{ infra__redhat_cluster_mount_point }}"
    state: directory
    mode: '0755'
  tags: nfs

- name: Create temporary mount point for NFS setup
  ansible.builtin.file:
    path: "/tmp/nfs_temp_mount"
    state: directory
    mode: '0755'
  run_once: true
  delegate_to: "{{ infra__redhat_cluster_nodes[0].hostname }}"
  tags: watchdog

- name: Enable high availability repository
  ansible.builtin.command: subscription-manager repos --enable "rhel-9-for-x86_64-highavailability-rpms"
  register: repo_result
  changed_when: repo_result.rc != 0
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "9"
  tags: high-availability
  
