---
- name: Update all packages
  dnf:
    name: "*"
    state: latest
  tags: update

- name: Set hostname
  hostname:
    name: "{{ ansible_hostname }}"
  tags: hostname

- name: Configure /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  tags: hosts

- name: Configure firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ firewall_services }}"
  tags: firewall

- name: Reload firewall
  command: firewall-cmd --reload
  changed_when: false
  tags: firewall

- name: Create mount point directory
  file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0755'
  tags: nfs

- name: Create temporary mount point for NFS setup
  file:
    path: "/tmp/nfs_temp_mount"
    state: directory
    mode: '0755'
  run_once: true
  delegate_to: "{{ cluster_nodes[0].hostname }}"
  tags: watchdog

- name: Temporarily mount NFS share
  mount:
    path: "/tmp/nfs_temp_mount"
    src: "{{ nfs_server }}:{{ nfs_share }}"
    fstype: nfs
    opts: "noatime,sync"
    state: mounted
  run_once: true
  delegate_to: "{{ cluster_nodes[0].hostname }}"
  tags: watchdog

- name: Create witness directory on NFS
  file:
    path: "/tmp/nfs_temp_mount/witness"
    state: directory
    mode: "0755"
  run_once: true
  delegate_to: "{{ cluster_nodes[0].hostname }}"
  tags: watchdog

- name: Unmount temporary NFS share
  mount:
    path: "/tmp/nfs_temp_mount"
    state: unmounted
  run_once: true
  delegate_to: "{{ cluster_nodes[0].hostname }}"
  tags: watchdog

- name: Remove temporary mount point
  file:
    path: "/tmp/nfs_temp_mount"
    state: absent
  run_once: true
  delegate_to: "{{ cluster_nodes[0].hostname }}"
  tags: watchdog

- name: Create mount point for witness
  file:
    path: "{{ watchdog_nfs_witness_dir }}"
    state: directory
    mode: "0755"
  tags: watchdog

- name: Mount NFS witness directory
  mount:
    path: "{{ watchdog_nfs_witness_dir }}"
    src: "{{ nfs_server }}:{{ nfs_share }}/witness"
    fstype: nfs
    opts: "noatime,sync"
    state: mounted
  tags: watchdog

